### ISSUE TITLE
Missing lifecycle task for the grunt-build-lifecycle plugin

### ISSUE THREAD

**Issue by agnitiogitsfera** [wmluke/grunt-build-lifecycle#1]
I always have warn: Missing lifecycle task for the grunt-build-lifecycle plugin
but in gruntinit I have: 
        lifecycle: {
            validate: [
                'jshint',
                'csslint'
            ]
        }

**Comment by eastmanenator** [comment]
You must to add grunt.loadNpmTasks('grunt-build-lifecycle'); after grunt.initConfig declaration.

**Comment by wmluke** [comment]
Yes, eastmanenator is correct.  Please add `grunt.loadNpmTasks('grunt-build-lifecycle')` after the `grunt.initConfig` declaration.
